"""test

Revision ID: 073d64e5dcca
Revises: b568b02e5fa2
Create Date: 2023-09-16 18:26:11.015768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '073d64e5dcca'
down_revision: Union[str, None] = 'b568b02e5fa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worktime', sa.Column('test', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('worktime', 'test')
    # ### end Alembic commands ###
