"""change WorkTime

Revision ID: 99625c030652
Revises: 943502f717bd
Create Date: 2023-09-18 21:54:21.634463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99625c030652'
down_revision: Union[str, None] = '943502f717bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('worktime', 'id', existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.add_column('worktime', sa.Column('month_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('worktime', 'month_id')
    # ### end Alembic commands ###
