from .fltrs import all_filters
from .start import router_start
from .statement_buttons import router_statement
from .url_button import router_url
from .today_button import router_today
from .lebedki_button import router_lebedki
from .calendar_button import router_calendar
from .back_button import router_back
from .callbacks import router_callbacks
from .time_table_buttons import router_time_table
from .user_settings import router_user_settings
from .errors import router_error